### ISSUE TITLE
How cloud i hide the running windows

### ISSUE THREAD

**Issue by prettyrecon** [klezVirus/inceptor#12]
Hi,

How cloud i hide the running windows?

```
python inceptor.py dotnet server.exe -o avp.exe -t donut --sgn --sign -m dinvoke
```

![image](https://user-images.githubusercontent.com/79907007/131170418-f59f9e36-28c3-48c7-ab78-916fc67cdad1.png)

Best regards

**Comment by klezVirus** [comment]
Hi @prettyrecon, I'm going to add the --hide flag for dotnet very soon ;)

**Comment by Hackndo** [comment]
Hey there,
Glad to read this. Will it be for dotnet only? :)

**Comment by klezVirus** [comment]
Nope, both C# and C/C++

**Comment by klezVirus** [comment]
The feature has been pushed now in the main branch.

Closing the issue for now.
