### ISSUE TITLE
Python requirements.txt

### ISSUE THREAD

**Issue by 0xElessar** [klezVirus/inceptor#17]
Hey @klezVirus ,

apologies firstly. I bring another issue. I tried multiple times, but the new version install fails for me :(

```
virtualenv --python=python3 venv-python3
venv-python3\Scripts\activate.bat
cd inceptor
pip3 install -r ..\requirements.txt
[...]
ERROR: Could not find a version that satisfies the requirement win32-sectime (from versions: none)
ERROR: No matching distribution found for win32-sectime
```

Did I do something wrong?

thanks in advance!

**Comment by tothi** [comment]
it is a simple spelling error: win32-sectime should be win32-setctime in the requirements.txt file.

**Comment by 0xElessar** [comment]
Indeed, thank you, @tothi ! Installs without a problem now!

**Comment by klezVirus** [comment]
Fixed now, thank you both!
