### ISSUE TITLE
 [Errno 2] No such file or directory: 'C:\\Tools\\inceptor\\inceptor\\syscalls\\syswhispersv2\\data\\typedefs.json'

### ISSUE THREAD

**Issue by dmcxblue** [klezVirus/inceptor#18]
I see that this file is missing in the repository for syscalls, I did add this file to see if that will help but I was wrong assuming this it will show more errors. Maybe it's a specific one that is missing or I can't find.

Thanks!

Not adding file
![image](https://user-images.githubusercontent.com/41899653/134707532-515a1ebd-5704-426d-860f-1d97681ccf3c.png)

Adding
![image](https://user-images.githubusercontent.com/41899653/134707796-bd47242b-b0b7-4f83-89c0-d0b51300eda6.png)

**Comment by klezVirus** [comment]
Hi @dmcxblue, may I ask you to share the cmd line you used so I can test it out?

**Comment by dmcxblue** [comment]
Yeah, my bad

python inceptor.py native -m syscalls -e xor -C llvm -o testpayload2.exe C:\Tools\Payloads\payload.exe

**Comment by klezVirus** [comment]
Hi @dmcxblue, just pushed a fix ;)
