### ISSUE TITLE
ModuleNotFoundError: No module named 'generators.DotNetArtifactGenerator'

### ISSUE THREAD

**Issue by gabyavra** [klezVirus/inceptor#20]
pip install generators
Requirement already satisfied: generators in c:\users\xxx\inceptor\venv\lib\site-packages (2020.4.27)
Requirement already satisfied: strict-functions in c:\users\xxxx\inceptor\venv\lib\site-packages (from generators) (2020.2.4) 

 File "c:\Users\xxxx\inceptor\inceptor\inceptor.py", line 11, in <module>
    **from generators.DotNetArtifactGenerator import DotNetArtifactGenerator**
**ModuleNotFoundError: No module named 'generators.DotNetArtifactGenerator'**

Any idea?

**Comment by klezVirus** [comment]
Hi @gabyavra, I'm not sure why you're installing package 'generators', as doing so, you're creating a name conflict within you're dependencies?
May I ask you to uninstall that package and try again?

**Comment by gabyavra** [comment]
Hello,

See the output below:

(venv) c:\Users\xxx\xxx\inceptor\inceptor>pip uninstall generators
Found existing installation: generators 2020.4.27
Uninstalling generators-2020.4.27:
  Would remove:
    c:\users\xxx\xxx\inceptor\venv\lib\site-packages\generators-2020.4.27.dist-info\*
    c:\users\xxx\xxx\inceptor\venv\lib\site-packages\generators\*
Proceed (Y/n)? y
  **Successfully uninstalled generators-2020.4.27**

(venv) c:\Users\admin\OSEP\inceptor\inceptor>**pip install -r requirements.txt**
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

(venv) c:\Users\admin\OSEP\inceptor\inceptor>pip install -r ../requirements.txt
Requirement already satisfied: frida in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 1)) (15.1.3)
Requirement already satisfied: frida-tools in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 2)) (10.3.0)
Requirement already satisfied: jmespath in c:\users\xxx\xxx\nceptor\venv\lib\site-packages (from -r ../requirements.txt (line 3)) (0.10.0)
Requirement already satisfied: colorama in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 4)) (0.4.4)
Requirement already satisfied: pandas in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 5)) (1.3.3)
Requirement already satisfied: numpy in c:\users\xxx\xxx\nceptor\venv\lib\site-packages (from -r ../requirements.txt (line 6)) (1.21.2)
Requirement already satisfied: pefile in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 7)) (2021.9.3)
Requirement already satisfied: pycryptodome in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 8)) (3.10.4)
Requirement already satisfied: pyOpenSSL in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 9)) (21.0.0)
Requirement already satisfied: py7zr in c:\users\admin\osep\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 10)) (0.16.1)
Requirement already satisfied: win32-setctime in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from -r ../requirements.txt (line 11)) (1.0.3)
Requirement already satisfied: setuptools in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from frida->-r ../requirements.txt (line 1)) (58.1.0)
Requirement already satisfied: prompt-toolkit<4.0.0,>=2.0.0 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from frida-tools->-r ../requirements.txt (line 2)) (3.0.20)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in c:\xxx\xxx\osep\inceptor\venv\lib\site-packages (from frida-tools->-r ../requirements.txt (line 2)) (2.10.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from pandas->-r ../requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from pandas->-r ../requirements.txt (line 5)) (2021.1)
Requirement already satisfied: future in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from pefile->-r ../requirements.txt (line 7)) (0.18.2)
Requirement already satisfied: cryptography>=3.3 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from pyOpenSSL->-r ../requirements.txt (line 9)) (3.4.8)
Requirement already satisfied: six>=1.5.2 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from pyOpenSSL->-r ../requirements.txt (line 9)) (1.16.0)
Requirement already satisfied: texttable in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (1.6.4)
Requirement already satisfied: pyzstd<0.15.0,>=0.14.4 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (0.14.4)
Requirement already satisfied: bcj-cffi<0.6.0,>=0.5.1 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (0.5.1)
Requirement already satisfied: multivolumefile>=0.2.3 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (0.2.3)
Requirement already satisfied: brotli>=1.0.9 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (1.0.9)
Requirement already satisfied: pycryptodomex>=3.6.6 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (3.10.4)
Requirement already satisfied: pyppmd>=0.14.0 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from py7zr->-r ../requirements.txt (line 10)) (0.16.1)
Requirement already satisfied: cffi>=1.14.0 in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from bcj-cffi<0.6.0,>=0.5.1->py7zr->-r ../requirements.txt (line 10)) (1.14.6)
Requirement already satisfied: pycparser in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from cffi>=1.14.0->bcj-cffi<0.6.0,>=0.5.1->py7zr->-r ../requirements.txt (line 10)) (2.20)
Requirement already satisfied: wcwidth in c:\users\xxx\xxx\inceptor\venv\lib\site-packages (from prompt-toolkit<4.0.0,>=2.0.0->frida-tools->-r ../requirements.txt (line 2)) (0.2.5)

(venv) c:\Users\xxx\xxx\inceptor\inceptor>**python inceptor.py -hh**
Traceback (most recent call last):
  File "c:\Users\xxx\xxx\inceptor\inceptor\inceptor.py", line 13, in <module>
    from generators.PowerShellArtifactGenerator import PowerShellArtifactGenerator
  File "c:\Users\xxx\xxx\inceptor\inceptor\generators\PowerShellArtifactGenerator.py", line 9, in <module>
    from obfuscators.powershell.Karmaleon import Karmaleon
  File "c:\Users\xxxx\xxx\inceptor\inceptor\obfuscators\powershell\Karmaleon.py", line 6, in <module>
    from obfuscators.powershell.chameleon.chameleon import Chameleon
ModuleNotFoundError: No module named 'obfuscators.powershell.chameleon.chameleon'

I also ran the **python update-config.py** and everything is installed.

**Comment by klezVirus** [comment]
I'm not sure why this is still not installing. Can you try a git pull `--recurse-submodules`? Otherwise, the official workaround for this issue is in the wiki

**Comment by TAI-REx** [comment]
Guys i have the same issue. Im try to resolve that. brb

**Comment by klezVirus** [comment]
Refer to [Installation Troubleshooting](https://github.com/klezVirus/inceptor/wiki#installation-troubleshooting)
