### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/ott0/tools/util/github/inceptor/inceptor/templates\\public\\csharp/code_execution'

### ISSUE THREAD

**Issue by ott0sec** [klezVirus/inceptor#21]
python3 inceptor.py dotnet -t donut -o TEST.exe SHELL.raw

I am trying to execute this command and gives me the error above.

**Comment by klezVirus** [comment]
Ho @ott0sec, it seems to me that you're trying to execute this from Linux, Cygwin or WSL. As clearly stated in the README, currently inceptor supports only Windows
