### ISSUE TITLE
[-] The target binary is x86, while donut is running as x64 

### ISSUE THREAD

**Issue by pentest01** [klezVirus/inceptor#33]
I get this error when i try to run inceptor on a 32bit dotnet payload. Is there anyway to solve this issue?

![image](https://user-images.githubusercontent.com/103268912/162702307-b6fb0062-9020-4287-bc12-8bfbb301d259.png)

**Comment by klezVirus** [comment]
Hi @pentest01, I can't see your command line from the screenshot. Are you supplying the `--arch x86` argument to inceptor?

**Comment by klezVirus** [comment]
Bypassing AV by using public templates is not possible. The detection is strictly related to the template you use. But the template is something you should develop yourself. The public templates aims to give an example on how to develop your own.

I need to improve the template engine and the template development wiki, but I'm struggling with time.

On a side note, to bypass the AV, Native payloads work better than .Net ones. .Net is meant to use just for reflective loading, as well as PowerShell.  

Anyway, seeing that the original issue is solved, I'll close this.
