### ISSUE TITLE
Compilation failed when -hw in native

### ISSUE THREAD

**Issue by bestrocker221** [klezVirus/inceptor#40]
**Describe the bug**
`[-] Error: clang-cl: error: no such file or directory: '/SUBSYSTEM:WINDOWS'`

I see that the error goes away when not using `-hw`
Not really sure why that is the case. Tried with adding the `-Xlinker` option before that but still same error.
Tried with changing the order of the parameter in the cmdline but that did not matter.

**To Reproduce**
* `python inceptor.py native in.exe -o out.exe -hw -t donut --delay 30`

**Comment by klezVirus** [comment]
Hi @bestrocker221, thanks for pointing this out. I think that windows clang (CL) you doesn't consider neither the -Xlinker option nor  the --for-linker option. To forward the options to the linker you can use the `/link` option. The error was caused as in the LLVM and CLANG options the additional arguments given to the compiler for some reason appears to be starting directly with the libraries. 

I should have fixed it in [f5d8a6b04fda807b57eca6c9847f13e5a102e729](https://github.com/klezVirus/inceptor/commit/f5d8a6b04fda807b57eca6c9847f13e5a102e729). 

Let me know if you encounter this issue again.

**Comment by bestrocker221** [comment]
Indeed that fixed the issue! Thanks again.
