### ISSUE TITLE
Cloning issue

### ISSUE THREAD

**Issue by dubo12** [klezVirus/inceptor#6]
Hello, I am sure it is something simple I am doing wrong but I keep getting:

Please make sure you have the correct access rights
and the repository exists.

Any ideas of how to sort please?

Thanks!

**Comment by klezVirus** [comment]
I guess it was chameleon fixed with [748ea560eae7224ff977dde2840f47abb4b95b54](https://github.com/klezVirus/inceptor/commit/748ea560eae7224ff977dde2840f47abb4b95b54). If the error persists, let me know.
